/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import Logic.Players;
import com.sun.org.apache.bcel.internal.generic.AALOAD;
import java.awt.HeadlessException;

import java.awt.List;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import javax.swing.JOptionPane;
import jdk.nashorn.internal.objects.NativeRegExp;

/**
 * clase registrarse extiende desde el Frame
 * @author Kobem
 */
public class Login extends javax.swing.JFrame {

    JFOthelloPrincipal data = new JFOthelloPrincipal();

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblImagenTablero = new javax.swing.JLabel();
        jDialog1 = new javax.swing.JDialog();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();
        pnlPanelPrincipal = new javax.swing.JPanel();
        lblBienvenida = new javax.swing.JLabel();
        btnExit = new javax.swing.JButton();
        lblImagenOthello = new javax.swing.JLabel();
        btnLogin = new javax.swing.JButton();
        btnOnePlayer = new javax.swing.JButton();
        btnTwoPlayers = new javax.swing.JButton();
        jBAyuda = new javax.swing.JButton();

        lblImagenTablero.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/.I. 1.png"))); // NOI18N
        lblImagenTablero.setText("jLabel2");

        jScrollPane1.setViewportView(jTextPane1);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 331, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(45, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(35, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        pnlPanelPrincipal.setBackground(new java.awt.Color(0, 204, 204));
        pnlPanelPrincipal.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblBienvenida.setFont(new java.awt.Font("Times New Roman", 3, 36)); // NOI18N
        lblBienvenida.setForeground(new java.awt.Color(255, 255, 255));
        lblBienvenida.setText("¡Bienvenido a Othello!");
        pnlPanelPrincipal.add(lblBienvenida, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 60, -1, -1));

        btnExit.setText("Salir");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });
        pnlPanelPrincipal.add(btnExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 410, 120, 30));

        lblImagenOthello.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Captura de pantalla (2).png"))); // NOI18N
        pnlPanelPrincipal.add(lblImagenOthello, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 170, 400, 290));

        btnLogin.setText("Registrarse");
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });
        pnlPanelPrincipal.add(btnLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 300, 120, 30));

        btnOnePlayer.setText("1P vs CPU");
        btnOnePlayer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOnePlayerActionPerformed(evt);
            }
        });
        pnlPanelPrincipal.add(btnOnePlayer, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 190, 120, -1));

        btnTwoPlayers.setText("1P vs 2P");
        btnTwoPlayers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTwoPlayersActionPerformed(evt);
            }
        });
        pnlPanelPrincipal.add(btnTwoPlayers, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 240, 120, -1));

        jBAyuda.setText("Ayuda");
        jBAyuda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBAyudaActionPerformed(evt);
            }
        });
        pnlPanelPrincipal.add(jBAyuda, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 360, 120, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlPanelPrincipal, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 697, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlPanelPrincipal, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 619, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * método que contiene el botón de salir 
     * @param evt evento
     */
    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnExitActionPerformed
    
    /**
     * método que almacena el nombre del primer jugador
     */
    public String name = "";
    
    /**
     * método que contiene el botón de registrar
     * @param evt evento
     */
    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        Players player = new Players(); //NO BORRAR!

        System.out.println("Entra al login");
        try {
            name = JOptionPane.showInputDialog("Escriba su nombre");
            if (name.isEmpty()) {
                JOptionPane.showMessageDialog(null, "Digite un texto válido");
            } else {
                player.setName(name);
                data.playersList.add(player);
                System.out.println("tamano lista " + data.playersList.size());
                for (int i = 0; i < data.playersList.size(); i++) {
                    System.out.println("Y tiene los elementos: " + data.playersList.get(i).getName());
                }
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "No hay datos para registrar");
        }
    }//GEN-LAST:event_btnLoginActionPerformed

    /**
     * método que contiene el botón de un jugador
     * @param evt evento
     */
    private void btnOnePlayerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOnePlayerActionPerformed

        try {
            if (data.playersList.isEmpty()) {
                JOptionPane.showMessageDialog(null, "La lista esta vacia, por favor registrese");
            } else {
                String name = JOptionPane.showInputDialog("Escriba su nombre");
                if (name.isEmpty()) {
                    JOptionPane.showMessageDialog(null, "Digite un texto válido");
                } else {
                    for (int i = 0; i < data.playersList.size() + 1; i++) {
                        if (data.playersList.get(i).getName().equals(name)) {

                            System.out.println("Accediendo...");
                            JFOthelloPrincipal panel = new JFOthelloPrincipal();

                            panel.setVisible(true);
                            panel.lblPlayerOne.setText(name);
                            panel.lblPlayertwo.setText("");
                            panel.lblWhitePieces.setText("");
                            this.setVisible(false);
                        }
                    }
                }
            }
        } catch (Exception e) {
        }
    }//GEN-LAST:event_btnOnePlayerActionPerformed
    
    /**
     * método que almacena el nombre del segundo jugador
     */
    public String name2;
    
    /**
     * método que contiene el botón de dos jugadores
     * @param evt evento
     */
    private void btnTwoPlayersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTwoPlayersActionPerformed
        String aux = "";
        try {
            if (data.playersList.isEmpty() || data.playersList.size() < 2) {
                JOptionPane.showMessageDialog(null, "No hay jugadores suficientes para acceder a este modo");
            } else {
                String name1 = JOptionPane.showInputDialog("Escriba el nombre del primer jugador");
                if (name1.isEmpty()) {
                    JOptionPane.showMessageDialog(null, "Elementos vacios, digite texto");
                } else {
                    for (int i = 0; i < data.playersList.size(); i++) {

                        System.out.println(data.playersList.get(i).getName());
                        if (data.playersList.get(i).getName().equals(name1)) {
                            name2 = JOptionPane.showInputDialog("Escriba el nombre del segundo jugador");
                            for (int j = 0; j < data.playersList.size(); j++) {
                                if (data.playersList.get(j).getName().equals(name2)) {
                                    JFOthelloPrincipal panel = new JFOthelloPrincipal();
                                    panel.setVisible(true);
                                    panel.lblPlayerOne.setText(name1);
                                    panel.lblPlayertwo.setText(name2);
                                    this.setVisible(false);
                                }
                            }
                        }
                    }
                }
            }
        } catch (HeadlessException headlessException) {
        }
    }//GEN-LAST:event_btnTwoPlayersActionPerformed

    /**
     * método que contiene el botón de ayuda en la partida
     * @param evt evento
     */
    private void jBAyudaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBAyudaActionPerformed

        Help fichero = new Help(this, true);
        fichero.setVisible(true);
    }//GEN-LAST:event_jBAyudaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    
    /**
     * variables con los botones que aparecen en la interfase
     */
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnLogin;
    private javax.swing.JButton btnOnePlayer;
    private javax.swing.JButton btnTwoPlayers;
    private javax.swing.JButton jBAyuda;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextPane jTextPane1;
    private javax.swing.JLabel lblBienvenida;
    private javax.swing.JLabel lblImagenOthello;
    private javax.swing.JLabel lblImagenTablero;
    private javax.swing.JPanel pnlPanelPrincipal;
    // End of variables declaration//GEN-END:variables
}
